name: $ss_linkpad_app

on: [workflow_dispatch, push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: hyoo-ru/mam_build@master2
      with:
        package: 'ss/linkpad'
        modules: 'app'

    - uses: hyoo-ru/gh-deploy@v4.4.1
      if: github.ref == 'refs/heads/master'
      with:
        folder: 'ss/linkpad/app/-'
